name: claude_chat_clone
description: A lightweight Claude.ai alternative using the Anthropic API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.5
  
  # HTTP requests
  http: ^1.4.0
  
  # File handling
  file_picker: ^10.1.9
  
  # Local storage
  shared_preferences: ^2.5.3
  
  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_database: ^11.3.6
  cloud_firestore: ^5.6.11
  uuid: ^4.5.1
  intl: ^0.20.2
  logger: ^2.6.0
  firebase_storage: ^12.4.9
  equatable: ^2.0.7
  connectivity_plus: ^6.1.4
  dartz: ^0.10.1
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15
  mockito: ^5.4.6
  build_runner: ^2.5.4

flutter:
  uses-material-design: true