// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf9Pt7lh0EOGiM2O2K2q6A_Gx8YHX4mFc',
    appId: '1:270787491728:android:257e0f6b252aecaad32515',
    messagingSenderId: '270787491728',
    projectId: 'flaude-0625',
    databaseURL: 'https://flaude-0625-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flaude-0625.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3KVHmN2b2csH5o7i4qou4wojAidpuJNQ',
    appId: '1:270787491728:web:82f595aa6b452473d32515',
    messagingSenderId: '270787491728',
    projectId: 'flaude-0625',
    authDomain: 'flaude-0625.firebaseapp.com',
    databaseURL: 'https://flaude-0625-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flaude-0625.firebasestorage.app',
    measurementId: 'G-EZTL919JBJ',
  );

}